src/objects/Alert__c.object
<CustomObject>
    <fields>
        <fullName>Alert_Numbers__c</fullName>
        <label>Alert Numbers</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notifications__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Notifications</label>
        <referenceTo>Notifications__c</referenceTo>
        <relationshipName>Alerts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Close</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Alert</label>
    <nameField>
        <label>Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Notifications__c.object
<CustomObject>
    <fields>
        <fullName>Template_C_Sent__c</fullName>
        <description>Track the Date When Template C has been sent</description>
        <label>Template C Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Template_G_Sent__c</fullName>
        <label>Template G Sent</label>
        <type>DateTime</type>
    </fields>
    <label>Notifications</label>
    <nameField>
        <label>Notifications Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JO_updateAlertTest.cls
@istest
public class JO_updateAlertTest {
    
    static testMethod void JO_updateAlert(){
        
        List<Id> taskWhatID=new list<Id>(); 
        
        Notifications__c notif=new Notifications__c();
        notif.Template_C_Sent__c=datetime.newInstance(2017, 9, 11, 13, 3, 0);
        notif.Template_G_Sent__c=datetime.newInstance(2017, 12, 12, 13, 13, 10);
        insert notif;
        list<Notifications__c> nlist;
        
        list<Alert__c> altlist=new list<Alert__c>();
        Alert__c alt=new Alert__c();
        alt.Status__c='open';
        alt.Alert_Numbers__c='11';
        alt.Notifications__c=notif.id;
        insert alt;
        altlist.add(alt);
        
        List<Alert__c> alertList = [Select ID, Name, Status__c, Alert_Numbers__c from Alert__c where Notifications__c  =: notif.Id  and Status__c='open'];
        system.debug('The alert list is' +alertList);
        
        /*Alert__c alt1=new Alert__c();
        alt1.Status__c='open';
        alt1.Alert_Numbers__c='13';
        //alt1.Notifications__c=notif.id;
        insert alt1;
        altlist.add(alt1);*/
        
        system.assertequals(1,altlist.size());
        
        JO_updateAlert joup=new JO_updateAlert();
        JO_updateAlert.updateAlert(taskWhatID);
    }
    
}