src/objects/Customer_Config__c.object
<CustomObject>
    <fields>
        <fullName>Job_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>User Configs</relationshipLabel>
        <relationshipName>User_Configs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Json_Config__c</fullName>
        <label>Json Config</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>User_Config__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Config</label>
        <referenceTo>Customer_Config__c</referenceTo>
        <relationshipLabel>User Configs</relationshipLabel>
        <relationshipName>User_Configs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>View_Name__c</fullName>
        <label>View Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>User Config</label>
    <nameField>
        <displayFormat>UC{000000}</displayFormat>
        <label>User Config ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Jo_Alert__c.object
<CustomObject>
    <description>Admin can configure a new alert or can edit/delete an alert. He can assign or remove access of alerts for each job owner.</description>
    <fields>
        <fullName>Alert_Is_Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field will be used to make rules to be enabled or disabled from configuration point of view</description>
        <label>Alert Is Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Alert_Type__c</fullName>
        <label>Alert Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                    <default>true</default>
                    <label>Internal</label>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sort__c</fullName>
        <label>Sort</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Alert Master</label>
    <nameField>
        <label>Jo Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alerts Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Notifications__c.object
<CustomObject>
    <fields>
        <fullName>Jb_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Owner</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notification_Status__c</fullName>
        <label>Notification Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NEW</fullName>
                </value>
                <value>
                    <fullName>SUBM</fullName>
                </value>
                <value>
                    <fullName>CLAM</fullName>
                </value>
                <value>
                    <fullName>ACCD</fullName>
                </value>
                <value>
                    <fullName>REJD</fullName>
                </value>
                <value>
                    <fullName>NASP</fullName>
                </value>
                <value>
                    <fullName>NAS</fullName>
                </value>
                <value>
                    <fullName>CNCL</fullName>
                </value>
                <value>
                    <fullName>PNAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Notifications</label>
    <nameField>
        <label>Notifications Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <recordTypes>
        <fullName>AS</fullName>
        <active>true</active>
        <description>Application for service</description>
        <label>AS</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JO_AlertConfigControllerTest.cls
@isTest
private class JO_AlertConfigControllerTest
{
    @testSetup
  static void JO_AlertConfigController()
  {
     Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User testUser = new User(Alias = 'testUsr', Email='testUser_axiom01@testorg.com', 
                                 EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                 LocaleSidKey='en_US', ProfileId = p.Id, 
                                 TimeZoneSidKey='America/Los_Angeles', UserName='testUser@testorg01.com');
        insert testUser;               

		Id contactRecType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Dashboard User').getRecordTypeId();
		List<Contact> conList = new List<Contact>();
		Contact con1 = new Contact();
		con1.LastName = 'JO User one';
		con1.Email = 'abc@g.com';
		con1.RecordTypeId = contactRecType;
		con1.Related_User__c = testUser.Id;
		conList.add(con1);
		Contact con2 = new Contact();
		con2.LastName = 'JO User two';
		con2.Email = 'abc@g.com';
		con2.RecordTypeId = contactRecType;
		con2.Related_User__c = testUser.Id;
		conList.add(con2);
		insert conList;

		Id notiRecType = Schema.SObjectType.Notifications__c.getRecordTypeInfosByName().get('AS').getRecordTypeId();		
		List<Notifications__c> notList = new List<Notifications__c>();
		Notifications__c not1 = new Notifications__c();
		not1.RecordTypeId = notiRecType;
		not1.Name = 'Notification one';
		not1.Jb_Owner__c = con1.Id;
		not1.Notification_Status__c = 'SUBM';
		notList.add(not1);
		Notifications__c not2 = new Notifications__c();
		not2.RecordTypeId = notiRecType;
		not2.Name = 'Notification two';
		not2.Jb_Owner__c = con1.Id;
		not2.Notification_Status__c = 'SUBM';
		notList.add(not1);

		Id configDashRecType = Schema.SObjectType.Customer_Config__c.getRecordTypeInfosByName().get('JO Dashboard').getRecordTypeId();
        Customer_Config__c cust = new Customer_Config__c(); 
        cust.Job_Owner__c = con2.Id;        
        cust.View_Name__c = 'Default Dashboard';
        cust.RecordTypeId = configDashRecType;
        insert cust;        
      Id configAlertRecType = Schema.SObjectType.Customer_Config__c.getRecordTypeInfosByName().get('JO Alert').getRecordTypeId();
      Customer_Config__c cust1 = new Customer_Config__c(); 
      cust1.Job_Owner__c = con2.Id;        
      cust1.View_Name__c = 'Alert Configurations';
      cust1.RecordTypeId = configAlertRecType;
      cust1.Json_Config__c = '{"viewfields":[{"alertType":"External","Id":"a2O2F0000006I2OUAU","isEnabled":true,"isHidden":true,"joAlertName":"New Application Call Customer","selectedUserPriority":"High","sortOrder":2,"sysPriority":"High"},{"alertType":"External","Id":"a2O2F0000006I3WUAU","isEnabled":true,"isHidden":true,"joAlertName":"Send Request for Additional Email","selectedUserPriority":"High","sortOrder":3,"sysPriority":"High"}]}'; 
      cust1.User_Config__c= cust.Id;       
      insert cust1;
      
      
      Jo_Alert__c jOAlert = New Jo_Alert__c();
      jOAlert.Name = 'Inactive order start ZIOCF';
      joAlert.Alert_Type__c = 'External';
      joAlert.Alert_Is_Enabled__c = True;
      joAlert.Sort__c = 26;
      Insert joAlert;
	}
   static testMethod void getAlert(){
		Contact c1 = [SELECT id FROM contact where LastName='JO User two'];
       Customer_Config__c userConfigRec = [SELECT id FROM Customer_Config__c where View_Name__c = 'Default Dashboard'];
		Test.startTest();
		List<JO_Wrapper.JO_AlertConfigWrapper> joConfig = JO_AlertConfigController.getAlertWrapper(String.valueOf(c1.Id), userConfigRec);
		Test.stopTest();
		
	}
    
    static testMethod void userConfigAlert(){
		Contact c1 = [SELECT id FROM contact where LastName='JO User two'];
        String configRec = '{"viewfields":[{"alertType":"External","Id":"a2O2F0000006I2OUAU","isEnabled":true,"isHidden":true,"joAlertName":"New Application Call Customer","selectedUserPriority":"High","sortOrder":2,"sysPriority":"High"},{"alertType":"External","Id":"a2O2F0000006I3WUAU","isEnabled":true,"isHidden":true,"joAlertName":"Send Request for Additional Email","selectedUserPriority":"High","sortOrder":3,"sysPriority":"High"}]}'; 

       Customer_Config__c userConfigRec = [SELECT id FROM Customer_Config__c where View_Name__c = 'Default Dashboard'];
		Test.startTest();
		String configList = JO_AlertConfigController.userConfigForAlert(configRec,userConfigRec,String.valueOf(c1.Id));
			
		Test.stopTest();
		
	}
}