src/objects/Customer_Config__c.object
<CustomObject>
    <label>User Config</label>
    <nameField>
        <displayFormat>UC{000000}</displayFormat>
        <label>User Config ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Configs</pluralLabel>
    <recordTypes>
        <fullName>JO_Portfolio</fullName>
        <active>true</active>
        <label>JO Portfolio</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Notifications__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Notifications (Customer)</relationshipLabel>
        <relationshipName>Notification_Customer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Jb_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Owner</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NotifDate__c</fullName>
        <label>Date of Notification</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NotifPriorityType__c</fullName>
        <label>Priority Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NotifPriority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NotificationDesc__c</fullName>
        <label>Notification Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NotificationType__c</fullName>
        <label>Notification Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AS</fullName>
                    <label>AS – Application for service</label>
                </value>
                <value>
                    <fullName>ER</fullName>
                    <label>ER – Electric distribution asset replacement</label>
                </value>
                <value>
                    <fullName>GC</fullName>
                    <label>GC – Gas distribution corrective</label>
                </value>
                <value>
                    <fullName>GR</fullName>
                    <label>GR – Gas distribution asset replacement</label>
                </value>
                <value>
                    <fullName>WR</fullName>
                    <label>WR – Work requested by others (WRO)</label>
                </value>
                <value>
                    <fullName>SG</fullName>
                    <label>SG - Staging ERR only</label>
                </value>
                <value>
                    <fullName>S9</fullName>
                    <label>S9 - Electric staging</label>
                </value>
                <value>
                    <fullName>OD</fullName>
                    <label>OD - Order Notification</label>
                </value>
                <value>
                    <fullName>EC</fullName>
                    <label>EC – Electric distribution corrective</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notification_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notification_Status__c</fullName>
        <label>Notification Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NEW</fullName>
                </value>
                <value>
                    <fullName>SUBM</fullName>
                </value>
                <value>
                    <fullName>CLAM</fullName>
                </value>
                <value>
                    <fullName>ACCD</fullName>
                </value>
                <value>
                    <fullName>REJD</fullName>
                </value>
                <value>
                    <fullName>NASP</fullName>
                </value>
                <value>
                    <fullName>NAS</fullName>
                </value>
                <value>
                    <fullName>CNCL</fullName>
                </value>
                <value>
                    <fullName>PNAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Notifications</label>
    <nameField>
        <label>Notifications Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <recordTypes>
        <fullName>AS</fullName>
        <active>true</active>
        <description>Application for service</description>
        <label>AS</label>
    </recordTypes>
    <recordTypes>
        <fullName>WR</fullName>
        <active>true</active>
        <description>Work requested by others (WRO)</description>
        <label>WR</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>NotificationType__c</fullName>
        <label>Notification Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Notification Order</label>
        <referenceTo>Notifications__c</referenceTo>
        <relationshipName>Order_Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Orders</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JO_DynamicTableController.cls
public class JO_DynamicTableController {
    @AuraEnabled
    public static List<JO_Wrapper.PortfolioFields> generateTableRecords(String[] contactId,String viewId, Customer_Config__c userConfigRec){         
        List<JO_Wrapper.PortfolioFields> jsonStructureData = new List<JO_Wrapper.PortfolioFields>();        

        for(JO_Wrapper.PortfolioViews val: JO_Portfolio.generateConfigRec(contactId,userConfigRec).allViewLst){
            if(val.viewId == viewId){
                for(JO_Wrapper.PortfolioFields apiVal: val.viewfields){
                    if(apiVal.visible) jsonStructureData.add(apiVal);
                }
            }            
        }
        return jsonStructureData;
    }
    @AuraEnabled
    public static List<Notifications__c> getNotificationRec(String ObjectName, String[] fieldstoget, List<String> contactIds,  Customer_Config__c userConfigRec){ 
        
        List<Notifications__c> notifRecords = [SELECT ID,Name,Jb_Owner__r.Name,Notification_Order__r.Name, NotificationDesc__c,CreatedBy.Name,NotificationType__c,Customer__r.Name,
                                               NotifPriority__c,NotifPriorityType__c,NotifDate__c,Notification_Status__c 
                                               FROM Notifications__c 
                                               WHERE Jb_Owner__c IN:contactIds AND NotificationType__c IN('AS','WR') AND NotifPriorityType__c IN('High','Low','Medium') LIMIT 100];
        return notifRecords; 
    }
}