src/objects/Email_Template_Master__c.object
<CustomObject>
    <fields>
        <fullName>Business_Name__c</fullName>
        <label>Business Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Template__c</fullName>
        <externalId>true</externalId>
        <label>Email Template</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Email Template Master</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Template Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Notifications__c.object
<CustomObject>
    <fields>
        <fullName>ApplicantAddress__c</fullName>
        <formula>Customer__r.MailingCity   + BR() + 
Customer__r.MailingState + &quot; &quot;  + Customer__r.MailingCountry + BR() +
Customer__r.MailingStreet+ &quot; &quot;  + Customer__r.MailingPostalCode</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ApplicantAddress</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Email__c</fullName>
        <formula>Customer__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Notifications (Customer)</relationshipLabel>
        <relationshipName>Notification_Customer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EmailTemplateDate__c</fullName>
        <formula>CASE( 
MONTH(today()), 
1, &quot;January&quot;, 
2, &quot;February&quot;, 
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;, 
7, &quot;July&quot;, 
8, &quot;August&quot;, 
9, &quot;September&quot;, 
10, &quot;October&quot;, 
11, &quot;November&quot;, 
&quot;December&quot; 
)+ &quot; &quot; + 
TEXT(DAY (today())) + &quot;, &quot; + 
TEXT(YEAR (today()))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EmailTemplateDate</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Jb_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Owner</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JobOwnerEmail__c</fullName>
        <label>Job Owner Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Notification_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Notifications</label>
    <nameField>
        <label>Notifications Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>EmailTemplateDate__c</fullName>
        <formula>CASE( 
MONTH(today()), 
1, &quot;January&quot;, 
2, &quot;February&quot;, 
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;, 
7, &quot;July&quot;, 
8, &quot;August&quot;, 
9, &quot;September&quot;, 
10, &quot;October&quot;, 
11, &quot;November&quot;, 
&quot;December&quot; 
)+ &quot; &quot; + 
TEXT(DAY (today())) + &quot;, &quot; + 
TEXT(YEAR (today()))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EmailTemplateDate</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Notification Order</label>
        <referenceTo>Notifications__c</referenceTo>
        <relationshipName>Order_Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Orders</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JO_Custom_Email.cls
public class JO_Custom_Email 
{
    @AuraEnabled
    public static List<WrapperData> getSendData(string EmailID, string RecId) 
    {
        string UsID=UserInfo.getUserId();
        User activeUser=[select id,Name,Email from User where id=:UsID];
        String userEmail = activeUser.Email;
        Id rec=Id.valueof(RecId);
        String sObjName = rec.getSObjectType().getDescribe().getLabel(); 
        Notifications__c nf;
        Order__c ord;
        if(sObjName == 'Notifications')
        {
             nf=[select id,Name,Jb_Owner__c,Customer_Email__c,JobOwnerEmail__c,ApplicantAddress__c,Customer__c,EmailTemplateDate__c from Notifications__c where id=:RecId];
        }
        else if(sObjName == 'Orders')
        {
             ord=[select id,Name,Notification_Order__c,Notification_Order__r.EmailTemplateDate__c,Notification_Order__r.JobOwnerEmail__c,Notification_Order__r.Jb_Owner__c,Notification_Order__r.Customer_Email__c,Notification_Order__r.ApplicantAddress__c from Order__c where id =: RecId];
        }
        
        Email_Template_Master__c emptmp=[select id,Name,Business_Name__c,Email_Template__c from Email_Template_Master__c where Email_Template__c=: EmailID];
        system.debug('Email master list==>'+emptmp);
       // EmailTemplate tmp=[select id, Name,Subject,CreatedDate,HtmlValue,Body,DeveloperName from EmailTemplate where id =: EmailID];
        Savepoint sp = Database.setSavepoint();
        Messaging.singleEmailMessage mail=new Messaging.singleEmailMessage();
        
        mail.setTemplateId(emptmp.Email_Template__c); 
        if(sObjName == 'Notifications')
        {
            mail.setToAddresses(new String[] { nf.JobOwnerEmail__c });
            system.debug('Contact Id==>>'+nf.Jb_Owner__c);
            mail.setWhatId(nf.Id);
            system.debug('Contact Id==>>'+nf.Jb_Owner__c);
            mail.setTargetObjectId(nf.Jb_Owner__c);
        }
        else if(sObjName == 'Orders'){
            mail.setToAddresses(new String[] { ord.Notification_Order__r.JobOwnerEmail__c });
            mail.setWhatId(ord.Id);
            system.debug('Contact Id==>>'+ord.Notification_Order__r.Jb_Owner__c);
            mail.setTargetObjectId(ord.Notification_Order__r.Jb_Owner__c);
        }
        mail.setSaveAsActivity(false);
        mail.setTreatTargetObjectAsRecipient(false); 
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        Database.rollback(sp);
        string HtmlBody=mail.getHtmlbody();
        List<WrapperData> wrapEmailList = new List<WrapperData>();
        string UserEmal;
        string CustomerEmail;
        string Htmltmpbody;
        string subject;
        string businessname;
        if(sObjName == 'Notifications')
        {
            UserEmal=userEmail;
            CustomerEmail=nf.Customer_Email__c;
            Htmltmpbody=HtmlBody;
            subject=emptmp.Name;
            businessname=emptmp.Business_Name__c;
            wrapEmailList.add(new wrapperData(UserEmal,CustomerEmail,Htmltmpbody,subject,businessname));
        }
        else if(sObjName == 'Orders')
        {
            UserEmal=userEmail;
            CustomerEmail=ord.Notification_Order__r.Customer_Email__c;
            Htmltmpbody=HtmlBody;
            subject=emptmp.Name;
            businessname=emptmp.Business_Name__c;
            wrapEmailList.add(new wrapperData(UserEmal,CustomerEmail,Htmltmpbody,subject,businessname));
        }
        return wrapEmailList;
    }
    @AuraEnabled
    public static void addfiledata(String EmailID,String fileName, String base64Data, String contentType) 
    {
        
        base64Data = EncodingUtil.urlDecode(base64Data, 'UTF-8');
        List<Attachment> aad = new List<Attachment>();
        Attachment a = new Attachment();
        a.parentId = EmailID;
        a.Body = EncodingUtil.base64Decode(base64Data);
        a.Name = fileName;
        a.ContentType = contentType;
        system.debug('Email Tempalte Id==>'+EmailID);
        insert a;
    }
    @AuraEnabled
    public static void sendEmailTCust(string EmailAdd,string Subject,string Html,string RecordId,string EmailID) 
    {
        system.debug('Template Id==>>'+EmailID);
        List<Messaging.SingleEmailMessage> mails =  new List<Messaging.SingleEmailMessage>();  
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        List<String> sendTo = new List<String>();
        sendTo.add(EmailAdd);
        mail.setToAddresses(sendTo);
        mail.setSenderDisplayName(Subject); 
        mail.setSubject(Subject);
        mail.setHtmlBody(Html);
        mail.setTargetObjectId(UserInfo.getUserId());
        mail.setTreatTargetObjectAsRecipient(false); 
        List<Messaging.Emailfileattachment> fileAttachments = new List<Messaging.Emailfileattachment>();
        for (Attachment a : [select Name, Body, BodyLength from Attachment where ParentId = :EmailID])
        {
            Messaging.Emailfileattachment efa = new Messaging.Emailfileattachment();
            efa.setFileName(a.Name);
            efa.setBody(a.Body);
            fileAttachments.add(efa);
        }
        mail.setFileAttachments(fileAttachments);
        mail.setWhatId(RecordId);
        mails.add(mail);
        Messaging.sendEmail(mails);
    }
    public class WrapperData
    {
        @Auraenabled
        public string UserEmail {get; set;}
        @Auraenabled
        public string CustomerEmail {get; set;}
        @Auraenabled
        public string Htmlbody {get; set;}
        @Auraenabled
        public string subject {get; set;}
        @Auraenabled
        public string businessname {get; set;}
        public wrapperData(string UserEmail,string CustomerEmail,string Htmlbody,string subject,string businessname)
        {
            this.UserEmail=UserEmail;
            this.CustomerEmail=CustomerEmail;
            this.Htmlbody=Htmlbody;
            this.subject=subject;
            this.businessname=businessname;
        }
    }
}