src/objects/Email_Template_Master__c.object
<CustomObject>
    <fields>
        <fullName>Business_Name__c</fullName>
        <label>Business Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Template__c</fullName>
        <externalId>true</externalId>
        <label>Email Template</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Record_Type__c</fullName>
        <label>Object Record Type</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Object_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AS</fullName>
                    <default>true</default>
                    <label>AS</label>
                </value>
                <value>
                    <fullName>WR</fullName>
                </value>
                <value>
                    <fullName>E060</fullName>
                </value>
                <value>
                    <fullName>E080</fullName>
                </value>
                <value>
                    <fullName>EC</fullName>
                </value>
                <value>
                    <fullName>ER</fullName>
                </value>
                <value>
                    <fullName>GC</fullName>
                </value>
                <value>
                    <fullName>GR</fullName>
                </value>
                <value>
                    <fullName>OD</fullName>
                </value>
                <value>
                    <fullName>OM</fullName>
                </value>
                <value>
                    <fullName>Other Notification</fullName>
                </value>
                <value>
                    <fullName>P1</fullName>
                </value>
                <value>
                    <fullName>P3</fullName>
                </value>
                <value>
                    <fullName>S9</fullName>
                </value>
                <value>
                    <fullName>SG</fullName>
                </value>
                <value>
                    <fullName>E070</fullName>
                </value>
                <value>
                    <fullName>G060</fullName>
                </value>
                <value>
                    <fullName>G070</fullName>
                </value>
                <value>
                    <fullName>G080</fullName>
                </value>
                <value>
                    <fullName>Parent Order</fullName>
                </value>
                <value>
                    <fullName>Sub Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <label>Object Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Notification</fullName>
                    <default>true</default>
                    <label>Notification</label>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Email Template Master</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Email Template Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Notifications__c.object
<CustomObject>
    <fields>
        <fullName>Notification_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Notifications</label>
    <nameField>
        <label>Notifications Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Notification_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Notification Order</label>
        <referenceTo>Notifications__c</referenceTo>
        <relationshipName>Order_Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Orders</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JO_Communication_Template.cls
public class JO_Communication_Template{
    private static Set<Id> taskWhatIDs = new set<Id>();
    @AuraEnabled
    public static List<WrapperData> getEmailtemplate(string RecId) {
        List<Email_Template_Master__c> Emlst;
        List<Notifications__c> Notifilst = [SELECT Id,Name, Notification_Order__c FROM  Notifications__c WHERE Id =:RecId];
        List<Order__c> ordlst=[select id,Name,Notification_Order__c from Order__c where id =: RecId];
        if(Notifilst.size() >0)
        {
            Emlst =[SELECT Id,Name, Email_Template__c,Business_Name__c,Sort_Order__c,Object_Type__c,Object_Record_Type__c,Is_Active__c FROM Email_Template_Master__c where Object_Type__c='Notification' order by Sort_Order__c ];
        }
        else
        {
            Emlst =[SELECT Id,Name, Email_Template__c,Business_Name__c,Sort_Order__c,Object_Type__c,Object_Record_Type__c,Is_Active__c FROM Email_Template_Master__c where Object_Type__c='Order' order by Sort_Order__c ];
        }
        for(Notifications__c lst :Notifilst)
        {
            taskWhatIDs.add(lst.Id);
        }
        for(Order__c ord : ordlst)
        {
            taskWhatIDs.add(ord.Id);
        }
        
        List<EmailMessage> emmes=[SELECT id,MessageDate,RelatedToId,Status,Subject,CreatedBy.Name FROM EmailMessage where RelatedToId In : taskWhatIDs order by CreatedDate DESC ];        
        List<WrapperData> wrapEmailList = new List<WrapperData>();
        Map<String,Integer> recordcount=new Map<String,Integer>(); 
        for(Email_Template_Master__c em : Emlst)
        {
            wrapEmailList.add(new wrapperData(null,'',em,'',0));
        }
        for(EmailMessage tk : emmes)
            {
                
                system.debug(tk.Subject +'<<===Record Count ==>>'+recordcount);
                
                if(recordcount.get(tk.Subject) != null){
                    recordcount.put(tk.Subject, recordcount.get(tk.Subject)+1) ;                
                }
                else {
                    recordcount.put(tk.Subject, 1);
                }
                
            }
        for(WrapperData w : wrapEmailList)
        {
            for(EmailMessage tk : emmes)
            {
                if(w.EmailTemp.Name.contains(string.valueof(tk.Subject)))
                {
                    w.SentDate=tk.MessageDate;
                    w.SentByName=tk.CreatedBy.Name;
                    w.EmailmessageId=tk.id;
                    break;
                }
            }
            
            w.recordCount = recordcount.get(w.EmailTemp.Name);
        }
        
        return wrapEmailList;
    }
    public class WrapperData
    {
        @Auraenabled
        public DateTime  SentDate {get; set;}
        @Auraenabled
        public string SentByName {get; set;}
        @Auraenabled public Integer recordCount {get; set;}
        @Auraenabled
        public Email_Template_Master__c EmailTemp {get; set;}
        @Auraenabled
        public string EmailmessageId {get; set;}
        @Auraenabled
       @testvisible public string EmailTempName 
        {
            get
            {
                return EmailTemp.Name;
            }
        }
        public wrapperData(DateTime  SentDate,string SentByName,Email_Template_Master__c EmailTemp,string EmailmessageId, Integer recordCount)
        {
            this.SentDate=SentDate;
            this.EmailTemp=EmailTemp;
            this.recordCount=recordCount;
            this.SentByName=SentByName;
            this.EmailmessageId=EmailmessageId;
        }
    }    
}