src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Notification_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Notification Order</label>
        <referenceTo>Notifications__c</referenceTo>
        <relationshipName>Order_Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Sub_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Orders</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JO_NotificationOrders.cls
public class JO_NotificationOrders{
/**
* On basis of field set, Create Dynamic SOQL
*/
    public static List<Schema.FieldSetMember> getFields() {
        return SObjectType.Order__c.FieldSets.OrderFieldset.getFields();
    }

    @AuraEnabled
    Public static List<Order__c> getAllNotifyOrders(String notifyId) {
        Id rec=Id.valueof(notifyId);
        String sObjName =rec.getSObjectType().getDescribe().getLabel();
        
        try
        {
            String query = 'SELECT ';
            for(Schema.FieldSetMember f : getFields()) {
                query += f.getFieldPath() + ', ';
            }
            if(sObjName == 'Notifications')
            {
                query += 'Id,('+query +'Id FROM Sub_Orders__r) FROM Order__c WHERE Notification_Order__c  = \''+ notifyId +'\'';
            }
            else if(sObjName == 'Orders')
            {
                query += 'Id,('+query +'Id FROM Sub_Orders__r) FROM Order__c WHERE Id  = \''+ notifyId +'\'';
                system.debug('query>>>>>'+query);
                system.debug('query11111>>>>>'+Database.query(query));
            }
            return Database.query(query);
        }
        catch(Exception e)
        {
            //addError('There is error while Fetching existing Question using Dynamic SOQL in Field Set. Error Detail - '+e.getMessage()); //This is Utility Method to display error message on VF Page
        }
        return null;
    }

 }